# Generated by Django 3.0.7 on 2020-06-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friendly_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='brakes',
            options={'verbose_name_plural': 'Brakes'},
        ),
        migrations.AddField(
            model_name='brakes',
            name='description',
            field=models.TextField(default='No Details'),
        ),
        migrations.AddField(
            model_name='brakes',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='brakes',
            name='name',
            field=models.CharField(default='No Name', max_length=254),
        ),
        migrations.AddField(
            model_name='brakes',
            name='price',
            field=models.DecimalField(decimal_places=2, default='No Price', max_digits=6),
        ),
        migrations.AddField(
            model_name='brakes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brakes.Categories'),
        ),
    ]
