# Generated by Django 3.0.7 on 2020-06-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0002_auto_20200620_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Gears',
        ),
        migrations.AlterModelOptions(
            name='gears',
            options={'verbose_name_plural': 'Gears'},
        ),
    ]
