# Generated by Django 3.0.7 on 2020-06-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0004_auto_20200621_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gears',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Gears',
        ),
    ]
