# Generated by Django 3.0.7 on 2020-08-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20200716_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
